export const FETCH_DATACARD_REQUEST = "FETCH_DATACARD_REQUEST";
export const FETCH_DEVICEDATACARD_SUCCESS = "FETCH_DEVICEDATACARD_SUCCESS";
export const FETCH_COMPANYDATACARD_SUCCESS = "FETCH_COMPANYDATACARD_SUCCESS";
export const FETCH_DATACARD_FAILURE = "FETCH_DATACARD_FAILURE";
