export const FETCH_AUTHLOGIN_REQUEST = "FETCH_AUTHLOGIN_REQUEST";
export const FETCH_AUTHLOGIN_SUCCESS = "FETCH_AUTHLOGIN_SUCCESS";
export const FETCH_AUTHLOGIN_FAILURE = "FETCH_AUTHLOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
